### PR TITLE
Fix keys not releasing when layers change

### LINKED ISSUE #125: Incorrect keycode released when layer is changed.
The incorrect keycode is released when the layer is changed *after* a key is pressed. Having a transparent layer above the key will mask the issue as it falls back to the correct layer.

https://discordapp.com/channels/719497620560543766/719544230497878116/747875909016617002

### PR DESCRIPTION
**Pull request by BrainWart**
This fixes #125 for me. The only shortfall I can see is that it doesn't drop through the layers any more for key release. If a key is transparent, it can only expect to receive a keypress event. I can't think of any uses for transparent keys at the moment.

To test the broken behavior:
key down A -> momentary/toggle a layer -> key up A
A will now be stuck pressed until pressed and released again.

Fixed:
key down A -> momentary/toggle a layer -> key up A
A is correctly released despite the layer change

### CODE REVIEW

File: app/src/keymap.c [hunk 1]
```diff
@@ -98,50 +97,62 @@ int zmk_keymap_layer_toggle(u8_t layer)
 		return zmk_keymap_layer_deactivate(layer);
 	}
 
-  	return zmk_keymap_layer_activate(layer);
+	return zmk_keymap_layer_activate(layer);
 };
 
-bool is_active_position(u32_t position, u8_t layer)
+bool is_active_position(u32_t position, u8_t current_layer, u32_t layer_state)
```
Comment (petejohanson) [inline app/src/keymap.c:103]: Seems like you can remove the `position` parameter here, since it's not used any more.

File: app/src/keymap.c [hunk 2]
```diff
@@ -191,11 +208,14 @@ int zmk_keymap_sensor_triggered(u8_t sensor_number, struct device *sensor)
...
 int keymap_listener(const struct zmk_event_header *eh)
 {
-	if (is_position_state_changed(eh)) {
+	if (is_position_state_changed(eh))
+	{
 		const struct position_state_changed *ev = cast_position_state_changed(eh);
 		return zmk_keymap_position_state_changed(ev->position, ev->state);
 #if ZMK_KEYMAP_HAS_SENSORS
-	} else if (is_sensor_event(eh)) {
+	}
```
Comment (petejohanson) [inline app/src/keymap.c:216]: I am strongly against this for conditionals, and mixed feelings about this for function definitions. Please revert these style related changes until we can actually fully settle on something. Thanks!

Comment (petejohanson) [reply app/src/keymap.c:216]: Reverting these changes will also make it easier to review just the fixes found here.
